/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jamf.regatta.core;

import org.junit.jupiter.api.Test;

class ClientTest {
    @Test void someLibraryMethodReturnsTrue() throws Exception {
        try (var client = new ClientBuilder().target("localhost:8443").build()) {
        }
    }
}
